data:
  file: "data/low-dimensional/f1_l-d_kp_10_269"
functions:
  fitness_function: True
  mutation_function: True
  #crossover_function possible options: one_point, two_point
  crossover_function: two_point
  #selection_function possible options: tournament, rank, roulette
  selection_function: tournament
configuration:
  pop_size: 100
  mutation_prob: 0.1
  generations: 50
  crossover_prob: 1.0